### ISSUE TITLE
“Search” field.

### ISSUE THREAD

**Issue by jensaymoo** [johannes-schliephake/nextcloud-passwords-ios#123]
Make the "search" field localizable.

**Comment by johannes-schliephake** [comment]
The search field is a bit special and is automatically translated by iOS. So now that the translation is fully integrated the search field is translated as well.

**Comment by jensaymoo** [comment]
Thanks!👍

Sent from ProtonMail for iOS

В Чт, сент. 30, 2021 в 00:12, Johannes Schliephake ***@***.***> пишет:
