### ISSUE TITLE
Search brings right result, then it disappears when clicking on it

### ISSUE THREAD

**Issue by HonkXL** [johannes-schliephake/nextcloud-passwords-ios#147]
I am using the search function of the App very often to search for entries.
Sometimes I get the problem, that I am doing a search, I am seeing the right entry in the search result. When clicking on it, the result diappears and a other result is shown in the lilst and opened.

Then I repeat this 3-4 times, then it works.

Screencast can provided on request.

**Comment by johannes-schliephake** [comment]
Thanks for reporting this behavoir. A video would help me out a lot. If you are uncomfortable with sharing a video of your passwords here, you can also send it directly to me: mail@cdslash.de

**Comment by HonkXL** [comment]
I just sent you the video using maildrop. I did a search for "Contabo". Then I clicked the result, the result was shown very short, then I came back to the search results for any other word. I repeated this.

**Comment by johannes-schliephake** [comment]
Thank you, your video helped me a lot in understanding the issue. It looks like the moment you tapped the result the auto-correction inserts a different search term. This updates the search results and therefore you are thrown back into the search view. So it's an easy fix; I will disable auto-correct with the next release.

**Comment by HonkXL** [comment]
This sounds great. Workaround for me is, not to use the search, but this is annoying.
Great to hear that it is easy to fix :-)

**Comment by johannes-schliephake** [comment]
Sorry it took a while to fix. I hope to release the next version containing the fix in the next 1-2 weeks!
