### ISSUE TITLE
Nice work! :D 

### ISSUE THREAD

**Issue by jancborchardt** [johannes-schliephake/nextcloud-passwords-ios#15]
Hi @johannes-schliephake – not an issue, just a note to let you know that this is super cool! And an invitation, because we have a Nextcloud Talk instance with various channels to connect contributors.

This includes a channel for all the mobile devs (iOS and Android) as well as one for the Passwords app, and more. Let me know if you are interested and I would invite you via your email address.

Cheers! :)

**Comment by johannes-schliephake** [comment]
Thank you so much for your kind feedback, @jancborchardt!
I would love to get in touch with more contributors. You can send the details to mail@cdslash.de :)
