### ISSUE TITLE
Crash after update to version 2.5

### ISSUE THREAD

**Issue by cmflouis** [johannes-schliephake/nextcloud-passwords-ios#165]
Hello Johannes,
First, let me thank you for your good work in making this app possible. I am using  it pretty much daily.  I am using iOS 14.8.1 on one of my device and after the upgrade at 2.5 the app crash.  I say to myself no problem so I reboot the device.  Same problem.  I say no problem I will erase the app and reinstall it.  Still crashing.  I don't know what you change in your app for version 2.5 but I am pretty sad to announce you that I cannot use it anymore on my iOS 14.x device.

Do you have any workaround or solution to that problem?

Best regards and keep your good work
cmflouis

**Comment by johannes-schliephake** [comment]
Hey, I'm really sorry to hear that.

Unfortunately I can't debug this myself because Apple doesn't provide simulators for iOS 14.8.x. I did test on 14.3 and 14.5 and both are working fine. So I need more details.

Which Passwords server version do you have installed? When does the crash happen, e.g. during app launch, after logging in, etc.?

**Comment by cmflouis** [comment]
Thank you for fast response. 
I use password the last version of January. 
The crash happen at the star of the application. I can’t open the app. 
This is on nextcloud 23. 
My environment with my iOS version was configured with nextcloud 22. That’s why I decided to delete the app and star fresh. I hope nothing stay stuck in my tablet that could prevent me from installing the app again with garbage in the location where the app is downloaded on the tablet. 
Regards. 
Louis

**Comment by johannes-schliephake** [comment]
Alright, because this is a fairy common setup I dug a bit deeper and it looks like this is a known bug in the most recent Xcode version (13.2.1). All release apps using SwiftUI and #availability checks will crash on iOS 14. I'll try to do a new build with an old version of Xcode.

**Comment by cmflouis** [comment]
Hello Johannes,
Thank you for helping me on this. As I told you before I am not a programmer so I was not aware of bugs in Xcode. I hope the new build will resolve the problem and won’t create other problems for you. I look forward to try your new version. 

Have a good day. 
Louis

**Comment by johannes-schliephake** [comment]
A new version of the latest update built using Xcode 13.0 is now available on the App Store.

To confirm this works as intended can you please update to v2.5.1, check if the app launches and give a quick feedback?

**Comment by cmflouis** [comment]
Hi Johannes,
Yep..  we are back to business. It is working in iOS 14.8.1 and 15.2. Thank you again for your efforts. I really appreciate. Moreover during the weekend. 
Less then 24 hours to react to a big problem. Congratulations!  

By the way what gives you this good idea to create a iOS client for this nextcloud app?  This is a great idea and I am happy to use it.
Continue your good work and have a good day. 
Louis

**Comment by johannes-schliephake** [comment]
Awesome, that's great to hear! Thank you for reporting this issue and giving feedback so quickly. This helped me a lot.

Also thank you for your praise. I guess the main reason why I chose to develop this app is that most Nextcloud apps already integrate really well with iOS, but a year ago the Passwords app was one of the last ones missing. I'm really happy this app is received so well.
