### ISSUE TITLE
Catalyst Support

### ISSUE THREAD

**Issue by BRadHoc** [johannes-schliephake/nextcloud-passwords-ios#169]
Hi,

First, great work on the app so far!

Is there any chance of getting this complied for catalyst?

**Comment by johannes-schliephake** [comment]
I looked into Catalyst again and while it's gotten much better, unfortunately it doesn't support AutoFill at all. That is only possible with fully native macOS apps.

I'm closing this issue in favor of #277 and will look into supporting macOS without Catalyst.
