### ISSUE TITLE
Offline Password Support

### ISSUE THREAD

**Issue by marc25v** [johannes-schliephake/nextcloud-passwords-ios#18]
Hi

i have over 300 passwords stored and every time I open the app it takes about 5-8 seconds for passwords to load. It seems the app is not caching a local version for immediate use. This would be a great feature. Similar to LastPass. 

Thanks !

**Comment by johannes-schliephake** [comment]
Yes, you are right, the app currently has no caching. But this is definitely one of the most important features on my list. It will take some time though to implemented caching securely.
