### ISSUE TITLE
Cannot authenticate with Nextcloud

### ISSUE THREAD

**Issue by DrMxxxxx** [johannes-schliephake/nextcloud-passwords-ios#180]
Hi,
Many thanks for your effort and the app!

I have the problem, that when I do a fresh install of the app and try to connect to my Nextcloud server, I only get a Screen with "Es ist ein Problem aufgetreten..." and nothing else happens. I can only try it again, but this doesn't work either.

How could I collect logs from the app itself? Logs from NC I do have.

Some data: 
NC on docker
Version 23.0.1

Thanks!

**Comment by johannes-schliephake** [comment]
Hey, really sorry to hear that!

Just to be 100% sure, you do have the app installed on your server as well? If so, maybe the logs from Nextcloud provide some details. The iOS app itself doesn't have a log. Can you post NC logs from the moment you are tapping "Try Again"?

**Comment by DrMxxxxx** [comment]
Hi,
sorry for the delay and thanks for your effort.

Here is a file with log lines - the first after a fresh install and the other after I pressed "Try again".
[nextcloud_passwords.log](https://github.com/johannes-schliephake/nextcloud-passwords-ios/files/8402335/nextcloud_passwords.log)

Greetings!
M

**Comment by johannes-schliephake** [comment]
Everything about that log file looks as expected. Is there anything special about your setup? LDAP, proxy, etc.?

**Comment by DrMxxxxx** [comment]
Hmm. No LDAP, just a (dumb) reverse proxy from Synology. But it does not much. Is there a timeout configured? Because sometimes the system is a little bit slow. Maybe the App is running into that.

**Comment by johannes-schliephake** [comment]
The timeout is iOS's default of 60 seconds. How long does it take to load for you?

To me this sounds like a very specific issue, although I can't really say if it's the app or the server. If you want to we can take a look at your setup together. Drop a message at mail@cdslash.de if you're interested.

**Comment by DanielKraemer** [comment]
@johannes-schliephake I also get an error while trying to sign in (no difference between login using normal password or app password)

Running NC 24.0.1 with the shown php modules installed
![2022-06-13_08-31](https://user-images.githubusercontent.com/49027330/173293766-fc350ff6-11c0-4e4f-b751-0834240a0403.png)

But I'm receiving the error shown within the log file

**Comment by ascpial** [comment]
I have the same issue. I'm investigating it.
Just a question for other people that have the same issue: what append if you try to export / import the passwords using the webapp?
On my side the website raises an error.

**Comment by ascpial** [comment]
I solved the problem on my side, by recreating some of my passwords that had a custom file entry.
I think these passwords were corrupted during an update, resulting in the inability to export the passwords and access them from the iOS application.

**Comment by johannes-schliephake** [comment]
Thank you for the details @ascpial, this is really interesting. Was there anything "uncommon" about those custom fields, for example special characters? @DrMxxxxx and @DanielKraemer, do you also make use of custom fields?

**Comment by johannes-schliephake** [comment]
Building on my last question: Do you remember if your passwords with custom fields are a bit older? From before mid 2019 to be more precise?

**Comment by DrMxxxxx** [comment]
> Building on my last question: Do you remember if your passwords with custom fields are a bit older? From before mid 2019 to be more precise?

I think I use these fields on older entries. I would have to go through all the passwords... :)

**Comment by DanielKraemer** [comment]
@johannes-schliephake I'm also using custom fields, also including the "file" field type

**Comment by johannes-schliephake** [comment]
Thanks for your feedback!

I might have a solution now. Looking through the server app's documentation and old commits it looks like in mid 2019 the JSON format for custom fields changed. Maybe there never was a migration from the old to the new format. So passwords with custom fields created before that time still could still have an outdated structure. This would explain why recreating passwords with custom fields solves the problem.

I added support for decoding those legacy custom fields. I will probably publish a TestFlight build with the changes for you, so we can make sure this actually fixes the problems you are seeing. So if it's OK for you please don't delete the custom fields in question until we have tested this.

**Comment by johannes-schliephake** [comment]
Here is a TestFlight build containing the possible fix: [https://testflight.apple.com/join/iuljLJ4u](https://testflight.apple.com/join/iuljLJ4u). Please give it a go, I would love to hear your feedback.

**Comment by DrMxxxxx** [comment]
> Here is a TestFlight build containing the possible fix: https://testflight.apple.com/join/iuljLJ4u. Please give it a go, I would love to hear your feedback.

Hello. Many thanks for the Fix, but I get the same error as before. You get the logs automatically or do I have to send it to you?

**Comment by johannes-schliephake** [comment]
Bummer! Well, maybe it fixes the issues at least for some users.

Regarding TestFlight: I only receive crash logs, but everything else has to happen manually. I uploaded a new build with some basic logging functionality. Could you check TestFlight if you have the latest build installed (21), go into the app's settings, tap "Log" and take a look at it? If it's OK for you, you can of course post it here or send it to me via Email: mail@cdslash.de.

**Comment by johannes-schliephake** [comment]
Finally found the issue! It was malformed custom fields, probably from other/outdated clients. The latest TestFlight build should be fully working. Thanks @DrMxxxxx for your help :)

**Comment by DanielKraemer** [comment]
@johanne-schliephake I tested it again today, still got the same issue in my logs as I already described within 

> @johannes-schliephake I also get an error while trying to sign in (no difference between login using normal password or app password)
> 
> Running NC 24.0.1 with the shown php modules installed ![2022-06-13_08-31](https://user-images.githubusercontent.com/49027330/173293766-fc350ff6-11c0-4e4f-b751-0834240a0403.png)
> 
> But I'm receiving the error shown within the log file [nextcloud-passwords-iOS-error_20220613.txt](https://github.com/johannes-schliephake/nextcloud-passwords-ios/files/8888548/nextcloud-passwords-iOS-error_20220613.txt)
> 
> Other Apps like Nextcloud, Nextcloud Talk and Nextcloud Deck are also using login via app-token and are working properly

**Comment by johannes-schliephake** [comment]
@DanielKraemer Could you install the TestFlight version (https://testflight.apple.com/join/iuljLJ4u), then try to authenticate again and check the iOS app's log under Settings?
