### ISSUE TITLE
Showing duplicate password entries for same entry

### ISSUE THREAD

**Issue by dandiodati** [johannes-schliephake/nextcloud-passwords-ios#188]
When I add a password it shows up multiple times. I believe it occurs when adding a new one from the app. On the nextcloud server only shows 1 entry. So if I delete one from the app they all vanish.Running nextcloud 23 iOS 15.

![image](https://user-images.githubusercontent.com/172809/163464860-58391b8a-b114-4fc1-ac39-74d75a7054b5.png)

**Comment by johannes-schliephake** [comment]
Is this happing every time you add a new password? Are all five PayPal entries in your screenshot from the same password?

**Comment by dandiodati** [comment]
Not quite sure what caused it but seems to be working now. I was happening
for the first couple passwords I made from the iPhone. Then created some
from the chrome extension and now
It’s working on iPhone. If I see it happen again will let you know.

FYI all duplicates on iPhone Passwords app pointed to one entry on the
server.

Dan

**Comment by johannes-schliephake** [comment]
Thanks for the details. I think I've seen this issue in older versions of the app, but I didn't come across it in recent versions. I will keep an eye on it.

**Comment by BrandonMFong** [comment]
I just wanted to note that I am seeing this too.  I started seeing this when I started using the passwords app on my ipad and iphone.  I always see at most 2 duplicate password entries on on the mobile applications. 

iPhone: iOS 16, iPhone 12
iPad: iPadOS 15.6.1, iPad Pro (11-inch) (3rd generation)
Nextcloud Passwords: version 2022.9.10

**Comment by johannes-schliephake** [comment]
I was able to reproduce this issue today. It's also the cause of #238. Should be fixed now, albeit with an ugly solution.
