### ISSUE TITLE
iPad | No Connection Could not connect to the Nextcloud Passwords instance.

### ISSUE THREAD

**Issue by wildernessfamily** [johannes-schliephake/nextcloud-passwords-ios#189]
**Background**
iPad 7
iOS: 15.2
Passwords App: 2.5.1

Hi,
I've been using SafeInCloud for years. I've also been using NextCloud for years. I decided to try Passman and found it very comparable to SafeInCloud. 
I have an Android phone and downloaded the Android version app and was able to connect with no problem. I also have the Firefox extension installed on my Macbook Pro and was able to connect with no problem.

I downloaded the app on my iPad but I keep getting an error.
When I open the app the first screen that appears is asking for the URL of my NextCloud server.
I enter the address. The blue 'Connect' lights up. I click 'Connect'. A mini-browser screen displays. I login into my NextCloud server. I get to the screen where I tap 'Grant'. It seems to connect. And then after about a second, I get a popup that says:

No Connection
Could not connect to the Nextcloud Password instance.

I've tried to uninstall and reinstall. I have Firefox as the default browser for the iPad. I tried changing to Safari. Nothing seems to work.

Any guidance would be greatly appreciated.
Thank you.

**Comment by johannes-schliephake** [comment]
Hey, are you using the Nextcloud Passwords app on your server? It sounds like you are using Passman. This iOS app is made for Nextcloud Passwords.

**Comment by wildernessfamily** [comment]
Hi,
I am using Passman. I decided to try out the NextCloud password extension. I didn't realize there were two different extensions. I saw the Passman extension first and clicked install. My apologies.

**Comment by johannes-schliephake** [comment]
No problem! If you want to you can still try Nextcloud Passwords. It's free and open source just like Passman and to my knowledge has pretty much the same features. There is a great import function in the web interface to migrate all your passwords.

**Comment by wildernessfamily** [comment]
Hi,
I installed NextCloud Passwords so that I can use your awesome iOS app :)
I'm not sure I will be able to continue to use NextCloud Passwords. There is one important feature missing. I'm just playing around with it so maybe I'm missing something.
Do you know if NextCloud Passwords supports TOTP aka 2FA authentication by an app? 
In today's world 2FA is a must. I try to use 2FA on every site that allows 2FA. I also make sure to choose TOTP and not other choices like SMS 2FA etc.
Do you know if NextCloud passwords support TOTP?
Also, thanks for taking the time to respond and creating a opensource app!

**Comment by johannes-schliephake** [comment]
You're in luck! The upcoming update (v2.6) supports OTP and will hopefully be released in the next few days. Just be aware that while OTPs are synced via your Nextcloud Passwords instance, they will for now only show up in the iOS client.

**Comment by wildernessfamily** [comment]
That's awesome! 
Thank you!
