### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [johannes-schliephake/nextcloud-passwords-ios#192]
https://hosted.weblate.org/projects/nextcloud-passwords-ios/#information says AGPL-only, but
Nextcloud upstream is AGPL-or-later.

It doesn't say either way here.

It can be fixed in
https://hosted.weblate.org/settings/nextcloud-passwords-ios/app
https://hosted.weblate.org/settings/nextcloud-passwords-ios/extention
https://hosted.weblate.org/settings/nextcloud-passwords-ios/provider
and
https://hosted.weblate.org/settings/nextcloud-passwords-ios/shared

**Comment by johannes-schliephake** [comment]
Hey, thanks for pointing this out! This project is completely independent from Nextcloud. Should I / Do I have to still change this?

To be honest I don't know the difference between -only and -later.

**Comment by comradekingu** [comment]
If it is AGPLv3-only, it means only AGPLv3 is possible, meaning it is an incompatibility with, and also not possible to move to AGPLv4 if that is ever released.

The strings can also only be used by AGPLv3 projects.

**Comment by johannes-schliephake** [comment]
I see! Thanks for your clarification. I changed all components to "AGPL v3.0 or later". Do you know if changes to the GitHub repo are necessary as well?

Also thank you so much for your translation! Is it ok for you if I add your name to the list of translatorsa and in the changelog?

**Comment by comradekingu** [comment]
@johannes-schliephake 
To be in complete compliance, you could tag up one of the source files with the copyright-holders of that file and 

> This program is free software: you can redistribute it and/or modify
> it under the terms of the GNU Affero General Public License as published
> by the Free Software Foundation, either version 3 of the License, or
> (at your option) any later version.

However just putting that at the bottom of the README will work with automated tools.
I just write AGPLv3+ somewhere since I find the text a bit too verbose.
