### ISSUE TITLE
Support for End-to-end Encryption 

### ISSUE THREAD

**Issue by nefh** [johannes-schliephake/nextcloud-passwords-ios#2]
Hi!
Great app, thank you very much for creating it, due to it I'm migrating from Passman to Passwords ;)

One problem visible at the very beginning - it does not connect to account if E2E encryption is set in the users setting on server. Without E2E everything works fine, but with E2E enabled, there is "An error occured..." message on passwords list. 

I enclose screenshot:

![IMG_9349](https://user-images.githubusercontent.com/35170530/105636116-fb41ca00-5e66-11eb-940d-5d2a59261e49.PNG)

Spec:
Nextcloud: 20.0.5
Passwords: 2021.1.2
Passwords-io: 1.0

**Comment by johannes-schliephake** [comment]
> due to it I'm migrating from Passman to Passwords ;)

Well, if that isn't a compliment, I don't know what is! :)

I hope i can make E2E work with the next version.

**Comment by huddx01** [comment]
> I hope i can make E2E work with the next version.

I also hope :-) 
This app is great! 
Would be perfect if your app could support e2e in next version.

**Comment by EKolyshkin** [comment]
Wanted to drop by to let you know you’re doing superb work! Having E2EE support is the only thing I need to start using your app. Gave you a tip by the way!

**Comment by jascharohr** [comment]
Great app! Would love to start using the it as well but also looking for E2EE. Send you a tip for the work so far, thank you!

**Comment by nefh** [comment]
Great news! Thanks!
