### ISSUE TITLE
NextCloud-Passwords on iOS (iPhone/iPad) with 2-Factor-Authentification

### ISSUE THREAD

**Issue by MWL1701** [johannes-schliephake/nextcloud-passwords-ios#220]
Hello,
I have been using the app on iOS for quite some time and am basically very satisfied with it! Very well implemented and works as desired.
However, recently I have had to use 2-factor authentication. Since then, unfortunately, I can no longer use the app on iOS.
I have created an app-password and logged in via token also with valid data. After that, however, immediately comes an error page from my provider!
If I test this identical with Android (Samsung phone) it works fine. Probably it must be the app on iOS ...
I can also gladly show the behavior if necessary.

One more note at the end: I once intentionally tried to enter a wrong app-password. When I do that I also get a message that the app-password is wrong and the login is rejected. --> Only with a successful login and the direct step after that I guess this error occurs.

Would be great if an investigation could be done on this in the short term and we could find a solution.
Gladly approach me: I support everything that is possible and necessary!
Best regards,
MW

**Comment by johannes-schliephake** [comment]
Hey, sorry to hear that!

This app uses Nextcloud's Login Flow v2 and doesn't need app passwords. You should be able to enter your Nextcloud credentials and then are asked to provide your second factor if one is set up. That is probably why an error page from your provider is shown instead of an error from the app.

Could you try to log in with your main Nextcloud credentials?

**Comment by MWL1701** [comment]
First I want to thank you very much for your investigation and your reply.
I now tested it again with my normal credentials and it surprisingly worked. I can't believe - and I would have swore that I tried this even more then once.
But the matter is solved then and I thank you very much.

**Comment by johannes-schliephake** [comment]
Awesome! Have fun using the app :)
