### ISSUE TITLE
URL cannot be entered

### ISSUE THREAD

**Issue by thor-sssd** [johannes-schliephake/nextcloud-passwords-ios#221]
Passwörter für Nextcloud 
Version 2.6.2

After starting this App the attached screen shows up to enter an HTTPS URL. But everything is greyed out and the App refuses any text input into the URL field. 

Any ideas about the root cause?

**Comment by thor-sssd** [comment]
![9250B5F3-6E62-4383-AE44-741A152EC601](https://user-images.githubusercontent.com/63791627/195298653-bab59b7a-71e3-432f-90a5-33e14f30f297.png)

**Comment by thor-sssd** [comment]
Workaround:
Attached screen is an overlay to the real App screen. After wiping down the real screen is visible and an URL can be entered.

**Comment by johannes-schliephake** [comment]
Hey, thanks for reporting this!

Unfortunately this is an issue with the SwiftUI framework. iOS 16.1 seems to have fixed it (Maybe even iOS 16.0, I'm not 100% sure). Sadly I can't do anything about these kinds of problems. Apple fixes SwiftUI bugs almost exclusively via OS updates. So for now swiping down and tapping the connect button is the only workaround.

Are you running iOS 15?

**Comment by rdratlos** [comment]
Yes, currently it's IOS 15. I'll come back after upgrading to IOS 16.

You're right it's somehow annoying but at least we have now documented a simple workaround. And it  just happens at first login. Subsequent logins work perfect.

**Comment by johannes-schliephake** [comment]
Because the issue seems to have reappeared on iOS 16.1.1 I fixed it myself instead of waiting for Apple. I'm not 100% sure if this is all it takes to prevent this problem from happening again, but we will see.
