### ISSUE TITLE
Can't use Hebrew to search passwords

### ISSUE THREAD

**Issue by tsfoni** [johannes-schliephake/nextcloud-passwords-ios#222]
For some reason I couldn't change the language from English to Hebrew to search for passwords.

**Comment by johannes-schliephake** [comment]
Hey, I'm not 100% sure what you mean by that.

The app isn't translated to Hebrew, if that is what you mean. However, the search should function independently from the app's language. I created a folder with a Hebrew name, searched for it and it got displayed as expected.

Could you further describe the issue or send screenshots/videos of the problem?

**Comment by tsfoni** [comment]
When trying to search for a password or folder, I can't change the language from English. 
This is happening only in your app.
Adding screenshot ->
![exmp](https://user-images.githubusercontent.com/104026572/200543849-89bc9c0c-c8ca-4f98-b65f-708bf3b595f8.jpg)

**Comment by johannes-schliephake** [comment]
Ah, I see, thank you for your description and screenshot.

I fixed the issue in the latest TestFlight build. You can join the beta here to check if the problem is resolved: https://testflight.apple.com/join/iuljLJ4u
