### ISSUE TITLE
Cannot link App to Nextcloud instance

### ISSUE THREAD

**Issue by mxwmnn** [johannes-schliephake/nextcloud-passwords-ios#231]
Getting this error message on nextcloud after login.
`[index] Fehler: Exception: OC\Core\Controller\ClientFlowLoginV2Controller::grantPage(): Argument #1 ($stateToken) must be of type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/core/Controller/ClientFlowLoginV2Controller.php' line 152 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controll ... {}, "grantPage")
1. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OC\\Core\\Contr ... r", "grantPage", OC\AppFramework\ ... {}, ["core.ClientFlowLoginV2.grantPage"])
2. /var/www/html/lib/base.php line 1047
   OC\Route\Router->match("/login/v2/grant")
3. /var/www/html/index.php line 36
   OC::handleRequest()

GET /login/v2/grant?
from censored by censored at 2022-11-27T13:52:49+00:00`

**Comment by johannes-schliephake** [comment]
Hey, thanks for reporting this.

To me, it looks like an issue on Nextcloud's side. The problem seems to happen during the login flow. The Passwords iOS app only displays Nextcloud's login window in a web view. What Nextcloud is doing in this window is unfortunately not under my control.

Just to be sure: Your login is successful and you can use the app, right?

**Comment by mxwmnn** [comment]
No i can't use the app. I always get the "some internal technical error" and I should watch the logs. Maybe I should try to reinstall nextcloud and try it again?

**Comment by johannes-schliephake** [comment]
That's weird. Which version of the app and which version of Nextcloud are you using? Can you post a screenshot of the error message?

**Comment by mxwmnn** [comment]
NC Version: 25.0.0
Passwords: 2.6.3

This is on the phone 
![image](https://user-images.githubusercontent.com/105636539/204158613-28d8a55e-f17c-4c91-ba6b-b6e8c8643e9a.jpeg)

And this the error message again 
`[index] Fehler: Exception: OC\Core\Controller\ClientFlowLoginV2Controller::grantPage(): Argument #1 ($stateToken) must be of type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/core/Controller/ClientFlowLoginV2Controller.php' line 152 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controll ... {}, "grantPage")
1. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OC\\Core\\Contr ... r", "grantPage", OC\AppFramework\ ... {}, ["core.ClientFlowLoginV2.grantPage"])
2. /var/www/html/lib/base.php line 1047
   OC\Route\Router->match("/login/v2/grant")
3. /var/www/html/index.php line 36
   OC::handleRequest()

GET /login/v2/grant?
fromby at 2022-11-27T20:39:35+00:00 `

**Comment by johannes-schliephake** [comment]
Thanks for the details.

Because the error is shown by Nextcloud's login window this is most likely a server side problem. But here are two ideas that came to my mind:
1. Can you update your Nextcloud instance to 25.0.1?
2. Do other Nextcloud apps on iOS have the same problem?

**Comment by johannes-schliephake** [comment]
Perfect, I'm glad to hear that!
