### ISSUE TITLE
Error when changing username/password for existing login credentials

### ISSUE THREAD

**Issue by dahumph** [johannes-schliephake/nextcloud-passwords-ios#238]
Hello,
recently I have the issue, when I try to edit the username or password for an existing login, the app throws a message that there is an error saving the password, original: „Beim bearbeiten des Passwortes ist ein Fehler aufgetreten“.
The credentials do not change in database.
iOS 16.1.2, app v 2.6.4, server latest stable.

**Comment by johannes-schliephake** [comment]
Hey, sorry to hear that.

Do you get the same error when you add a password and then try to edit it? Or is it an issue with specific passwords? Maybe just shared ones?

**Comment by dahumph** [comment]
Hello,
it turned out that there was a discrepancy between username stored in the serverside database and the ios app. Probably I edited this login username in the browser extension before and somehow it did not sync the changed credentials to the ios app. After further investigating this issue, it turned out that usernames edited in the browser extension do generally not sync with the ios app and also makes it impossible to change or delete this credentials in the ios app. I had to manually delete the entry in browser extension end set up a new one, which then does immediately sync to the ios app.

**Comment by dahumph** [comment]
Hello Johannes,
It`s not that I immediately try to edit again in ios app. Whenever I edit a username of an existing credential in the browser extension, the new username does not get synced to the ios app. Neither more time nor closing the ios app or manually refreshing the app does change that. Once edited in browser extension, the username of that specific credential stays unchanged in ios app and cannot be modified or even deleted in ios app. Deleting and setting up a new one in browser extension does sync properly and immediately to the ios app. Also vice versa, editing or setting up new credentials in ios app do sync immediately to server database.

**Comment by dahumph** [comment]
One simple thing solved the issue. I deleted the ios app and reinstalled...now editing in browser extension immediately syncs to the ios app...sorry for wasting your time, something must have been wrong on my instance of the app on the phone.
Thanks for providing and maintaining this app, I`m using it every day!

**Comment by johannes-schliephake** [comment]
Really weird behavior... Thanks for reporting it in detail. I will keep an eye on problems of this sort. Let's hope it was just a one-off :)

**Comment by johannes-schliephake** [comment]
I was able to reproduce this issue today. It's caused by #188. When such a rare duplicate entry occurs, all entries with alphabetically higher IDs can't be updated anymore. The duplicate entries should be fixed now and therefore the errors when updating some passwords should be no longer.
