### ISSUE TITLE
Login via App-Token is not recognised by Passwords App

### ISSUE THREAD

**Issue by mario-van-zadel** [johannes-schliephake/nextcloud-passwords-ios#240]
When logging in via "default" credentials (including OTP), everything's fine.

Now, I want to use an App Token to login by using the "Alternative Anmeldung mittels App-Token".

The login succeeds, but the modal login window isn't closed:
![2023-01-27-Bildschirmfoto 2023-01-27 um 17 59 46 png-7b0cbe520c6f519221da2e9c666666a0](https://user-images.githubusercontent.com/4664196/215149310-6e5209c2-74c3-45c2-9b7f-feb599d4c056.png)

Should the passwords app recognise this state or is there some kind of callback missing on Nextcloud's server side?

**Comment by johannes-schliephake** [comment]
I think I found the underlying issue. TestFlight build 31 contains a fix. Please note that this only applies to Nextcloud 25.0.3. Previous versions had a lot of issues with the login flow.
