### ISSUE TITLE
Unable to connect on my server on an unstandart port on iPad 

### ISSUE THREAD

**Issue by cmflouis** [johannes-schliephake/nextcloud-passwords-ios#244]
Hi Johannes,
I use your app every day. When I open the app on my iPad I realize that my synchronization does not work. So I decide to erase the app to reinstall it and reconnect to my server. I had a bad surprise that I am unable to connect to my server anymore on my iPad. My phone is works well though. 
Can you help me?
Thank you for your good work. 
Regards. 
cmflouis

**Comment by johannes-schliephake** [comment]
Hey, I'm sorry to hear that. What exactly happens on your iPad when you can't connect to your server? Where is it stuck?
Maybe a log from the app also contains some hints about the problem. For that you can install the TestFlight beta [here](https://testflight.apple.com/join/iuljLJ4u) and then open the log from the app's settings.

**Comment by cmflouis** [comment]
Hi Johannes,
here is more input to help you to help me.
Like you view in the screenshot on iPadOS the app just not communicate with the server. This is on and https unstandard port but in my lab I built it on standart 443 and I still have the same problem. The connection bouton stay gray. For what I see it is not relate with the version of nextcloud (25.0.3) even on Password app version (23.1.23).  I am on iPadOS 16.3. Iphone still work fine. I update information on the application in a browser and it was reflected in your password app on iOS. So this part work fine.
Hope that can help.
Regards.
cmflouis
![error password nextcloud ipad](https://user-images.githubusercontent.com/97805127/218266751-a0bcf3e4-6735-47bb-8291-395bc31e7ef9.jpg)

**Comment by cmflouis** [comment]
Supplemental,
I did not realize that was for so long that it did not work on iPadOS. I tried you suggestion to install testflight to realize that every version that is in testflight cannot connect to my nextcloud server. The connection button stay gray.
Have a great day.
cmflouis

**Comment by johannes-schliephake** [comment]
Thanks for the details. Does a little spinner animation still run a few seconds when you finish typing in your server URL? It should appear to the right of the URL. If so, could you please check the app's log? For that you have to use a TestFlight build, then try to connect to your server. After that failed you should see more information when you close the connect screen, go into settings and then tap the "Log" button.

**Comment by cmflouis** [comment]
Hi Johannes,
I did what you ask me and the only thing I see is logging enabled. I hope that could help you. 
![IMG_3168](https://user-images.githubusercontent.com/97805127/218287527-b8edb3f2-630a-4679-950b-82b91cb17804.jpeg)
.

**Comment by johannes-schliephake** [comment]
Thanks again for the details. I tried to reproduce your setup as far as I can, but I don't see the same issue. This might be a very specific problem. Would you be willing to share your server URL with me? I would only use it to reproduce the connection issues. You can send send me an Email to mail@cdslash.de with the URL, if you are OK with that.

**Comment by cmflouis** [comment]
Hello again,
I beginning by telling you that I nearly apologize for this error. Let me explain now.
You point me in the direction of URL. Hum? And she cannot reproduce the problem. Could that be on my side I tolld myself. And guest what? You were right. That was my bad. And here is where I apologize. Believe it or not I try to connect but not locally... by my vpn and guest what, again. It worked!!! Because in the setting of the application their is a toogle to give right ti access the local netwotk. It was not ON. Put that ON and it worked. I tought we could close the case and another problem arise. Not with the same device.

This iPad is in 15.7.3 and I don't know if it is related to the version of the OS because when I try to connect to my prod and my lab environnement I receive this message below after intering my credentials and it seem after googleling on the Internet that others persons pass thru this type on error. I give you the screeshot of the app error and the text below come from the logs of the server.
Again thank you for your good work
Text to you soon.
cmflouis
Client error
![IMG_3132](https://user-images.githubusercontent.com/97805127/218338483-7e06f18d-8811-4fa8-aa8f-c66aaf90de0e.jpg)

Server logs
[index] Error: Exception: OC\Core\Controller\ClientFlowLoginV2Controller::grantPage(): Argument #1 ($stateToken) must be of type string, null given, called in /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 225 in file '/var/www/html/nextcloud/core/Controller/ClientFlowLoginV2Controller.php' line 152 at <<closure>>

0. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controll ... {}, "grantPage")
1. /var/www/html/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OC\\Core\\Contr ... r", "grantPage", OC\AppFramework\ ... {}, ["core.ClientFlowLoginV2.grantPage"])
2. /var/www/html/nextcloud/lib/base.php line 1047
   OC\Route\Router->match("/login/v2/grant")
3. /var/www/html/nextcloud/index.php line 36
   OC::handleRequest()

GET /index.php/login/v2/grant?
from xx.xx.xx.xx by

**Comment by cmflouis** [comment]
Supplemental
Guest what?
The app works in nextcloud 26 beta 3.
Mind Buggling?!?
Regards.
cmflouis

**Comment by johannes-schliephake** [comment]
Oh, that's awesome to hear! I'm really happy everything works now as expected. Regarding the update to Nextcloud 26 Beta 3, after which the login started to work again: Nextcloud 25 had a few issues with logins for a handful of users. So if there are other issues when logging in, Nextcloud 26 might already have a fix.
