### ISSUE TITLE
Feature: AutoFill- 2fa

### ISSUE THREAD

**Issue by strich3** [johannes-schliephake/nextcloud-passwords-ios#247]
Add autofill for 2fa

**Comment by johannes-schliephake** [comment]
There already exists a Safari sharing extension for autofilling one-time passwords. You can find it in the sharing menu. Apple currently doesn't offer a native API for OTPs, so this is a good as it gets for now. 

![image](https://user-images.githubusercontent.com/26935664/225380176-276e3aae-a3b0-47ec-a019-7af1ed80cc58.jpeg)![image](https://user-images.githubusercontent.com/26935664/225380215-794e09c3-5c34-4070-80ba-6309b3a63923.jpeg)

**Comment by petter1** [comment]
![image](https://github.com/johannes-schliephake/nextcloud-passwords-ios/assets/13876117/41e6807c-8007-44ff-bc33-8172072c3747)

That seems like it changed with iOS 17. additionally, it seems like Apple 2FA codes aren't offered anymore if apple keychain isn't enabled, like it did with iOS 16. 
is the behavior the same for you?

**Comment by johannes-schliephake** [comment]
The features I described above are still available and working on iOS 17.

The first screenshot you posted just shows a feature where OTP codes scanned with the Camera app are handled by the password manager you select. This indeed isn't supported yet, but you can still set up OTPs from within the Passwords app.

The release notes are about Passkeys and Settings app deeplinking, two different features. Right now, Apple doesn't allow integration of third party OTP apps.

**Comment by petter1** [comment]
Thank you for clarification! 

I have now decided, that I want to use passkeys in the future and therefore, I migrated to strongbox since it supports sync to Linux using a KeePass file in my Nextcloud folder.
