### ISSUE TITLE
Feature: Using ports of the URLs for better Autofill

### ISSUE THREAD

**Issue by Samurai1201** [johannes-schliephake/nextcloud-passwords-ios#249]
First of all, love your App.

Similar to the browser addon for Nextcloud Passwords, that now has the functionality to also use ports added to the end of the URL to distinguish between different Websites (especially locally selfhosted ones).

I dont know if this is even possible with Apples Autofill system, so no big deal if its impossible.

Thanks for your work.

Danke für deine geniale Arbeit von einem Landsmann

**Comment by johannes-schliephake** [comment]
Thanks for your kind words!

There are two different algorithms when autofilling:

1. Apple's algorithm when using the QuickType keyboard (button above the keyboard to instantly fill in a matching password). Unfortunately, I have no way of altering the behavior here. The Passwords app tells the system for which URLs a password is available. Apple decides which URLs are matching a given website.
2. My own algorithm when launching the AutoFill provider (looks 99% like launching the full app). Here I can tweak the suggestions and their order. I did a few experiments with my algorithm and it seems to find all relevant passwords, but it doesn't make use of the port to bring the best match to the top of the list.

Which of those two situations is problematic for your use case?

**Comment by Samurai1201** [comment]
Mostly the Autofill Provider, since I have a server with multiple instances of Docker containers on different ports …
The suggestions already make a lot more sense than apples quicktype, but an option to take the port into consideration would really improve the experience for my usecase

**Comment by johannes-schliephake** [comment]
Ah, I see. Thanks for the details about your use case!

The algorithm is now including the port when ranking URLs. It might take a bit though until this is released.

**Comment by m-breitbach** [comment]
Sorry to warm this up, but how are subdomains treated? As far as I can see, passwords belonging to all related sudomains are offered, not even ordered. So on b.example.com, I get passwords offered for a., b., and c.example.com. Restricting that to exact matching subdomains (per option) or at least ordering it right would be nice.

**Comment by johannes-schliephake** [comment]
@m-breitbach No problem! Are you talking about the suggestions from the AutoFill UI (above the keyboard and the sheet that automatically pops up when visiting a login page) or when launching the app-like view with all passwords?

**Comment by m-breitbach** [comment]
I talk about the suggestions above the keyboard and in the pop-up. In the app-like view, the suggestion seems to be actually considering the subdomain correctly.

**Comment by johannes-schliephake** [comment]
That is unfortunately the part I can’t influence…

**Comment by m-breitbach** [comment]
Is it the ordering that cannot be influenced, or even the selection of entries that are presented? In the latter case, one could think about (optionally) matching only exact subdomains. In the former case, we are doomed.

**Comment by johannes-schliephake** [comment]
Unfortunately, it’s both. I would love to recommend Apple‘s Feedback Assistant for a feature request but unfortunately Apple ignores even bug reports.

**Comment by m-breitbach** [comment]
All right, got it, thanks!
