### ISSUE TITLE
Quick autofill support

### ISSUE THREAD

**Issue by MuhammedKpln** [johannes-schliephake/nextcloud-passwords-ios#253]
### Feature Description

Quick autofill as you can see from the screenshot below

![](https://keepassium.com/articles/quick-autofill/quick-autofill-ios.png)

### Rationale

It is much faster and has better UX.

**Comment by johannes-schliephake** [comment]
Hey, this is already fully supported. AutoFill has to be enabled selected by the user in iOS's settings app under the Passwords section. Instructions are also available in this app's settings.
