### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [johannes-schliephake/nextcloud-passwords-ios#254]
### Feature Description

How about adding multi Account Support? Like the nextcloud files App, so you can Connect to multiple nc instances :)

### Rationale

I think many people have a private nextcloud, a work / business nextcloud and maybe a third nextcloud from a different organisation.

**Comment by johannes-schliephake** [comment]
Duplicate of #128. I'm going to write some details over there :)
