### ISSUE TITLE
Connect button remains disabled

### ISSUE THREAD

**Issue by lucaquarium** [johannes-schliephake/nextcloud-passwords-ios#256]
### iOS App Version

2.6.7

### iOS Version

16.5.1

### Device Model

iPhone 14

### Nextcloud Server Version

27.0.1

### Server App Version

2023.8.31

### Peculiarities of Your Setup

Server behind a proxy

### Observed Behavior

When I enter the URL of my Nextcloud (https://cloud.maison/), the connect button remains gray/disabled, no matter the provided URL.

### Expected Behavior

I would like the connect button to deactivate.

### Debugging

- [X] I did install the [TestFlight](https://testflight.apple.com/join/iuljLJ4u) version to check the log on the app's *Settings* page → *Log*.
- [ ] I did check for iOS logs named *Passwords* under *System Settings* → *Privacy & Security* → *Analytics & Improvements* → *Analytics Data*.
- [ ] I did check for Nextcloud logs on the admin's *Logging* page.

### Logs

```shell
[4 août 2023 à 23:50] Logging enabled
```

**Comment by johannes-schliephake** [comment]
Hey, sorry to hear that. It sounds like the Login Flow v2 can't be initiated. Are you able to successfully log into other Nextcloud iOS Apps? E.g. the main app or Nextcloud Talk?

**Comment by lucaquarium** [comment]
Hi!

There is a small loading icon on the right for 1 or 2 seconds; it then disappears, but the connect button is still disabled.
The official Nextcloud app works fine; I haven't tried any other apps.
I also tried to get a valid https for my self-signed certificate by creating a certification authority, but without success.
Could this just be a UI problem?

**Comment by johannes-schliephake** [comment]
When the Connect button stays disabled usually the app can't find the server or the Nextcloud instance on that server. Is your instance installed into a subdirectory? E.g. https://cloud.maison/nextcloud? If so, you have to enter the full path to your instance. Apart from that the next step is to check Nextcloud admin logs. Do you have admin access for checking the logs after trying to connect the app?

**Comment by lucaquarium** [comment]
Nothing appears in /var/log/nginx/access.log; however, when I go to https://cloud.maison from a browser, the logs fill up.
I strongly suspect that my self-signed ssl certificate is being rejected by the Nextcloud Passwords application.

**Comment by johannes-schliephake** [comment]
Self-signed certificates are fully supported by the app. You should see an alert asking for confirmation when connecting via an invalid certificate. So that can't be the problem.

I added new logging calls to the latest TestFlight build. Can you update to build 36 and check the in-app log again?

**Comment by lucaquarium** [comment]
```
[12 août 2023 à 11:26] Logging enabled
[12 août 2023 à 11:26] URLError(_nsError: Error Domain=NSURLErrorDomain Code=-1009 "La connexion Internet semble interrompue." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x281990930 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, ipv6, dns, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <F8FBAC33-16DF-4DB3-9577-D10B2A3100C5>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
        "LocalDataTask <F8FBAC33-16DF-4DB3-9577-D10B2A3100C5>.<1>"
    ), NSLocalizedDescription=La connexion Internet semble interrompue., NSErrorFailingURLStringKey=https://cloud.maison/index.php/login/v2, NSErrorFailingURLKey=https://cloud.maison/index.php/login/v2, _kCFStreamErrorDomainKey=1})
```
Browser access to https://cloud.maison/index.php/login/v2 gives a code 405

**Comment by lucaquarium** [comment]
A POST request to the url gives me this
![image](https://github.com/johannes-schliephake/nextcloud-passwords-ios/assets/60423745/48245087-8090-49ba-9e1b-f6af5451a631)

**Comment by johannes-schliephake** [comment]
That's the error for when no network connection is available. 

In the iOS system settings there should be an entry for this app.
Can you check if local network access is visible and granted there?
Another idea: If you are using this app via cellular, did you disable cellular data for it?

**Comment by lucaquarium** [comment]
You've got it!
By default, access to the local network is disabled; enabling it works!
Thanks so much for your help! <3

![image](https://github.com/johannes-schliephake/nextcloud-passwords-ios/assets/60423745/8379c2c2-4cb1-486c-9f0d-99c7794ea39d)

**Comment by johannes-schliephake** [comment]
Awesome, I'm happy to hear that! Maybe I could automate this step, I'be seen other apps explicitly asking for this permission. I'll look into it at some point.
