### ISSUE TITLE
Cloud Copying does not work in app

### ISSUE THREAD

**Issue by dandiodati** [johannes-schliephake/nextcloud-passwords-ios#264]
### iOS App Version

2.7

### iOS Version

16.6

### Device Model

iPhone 12 pro

### Nextcloud Server Version

N/a

### Server App Version

N/a

### Observed Behavior

When coping a password by clicking on the field in the app it does not copy quite right. 
I can paste it locally but if I paste from my Mac computer it can’t find it (uses shared iCloud clipboard)

  I can make it work if i edit the password field select the text and copy then I can paste from the Mac.

so I think there is more then one clipboard for copying. The app seems to only use a local one and not the iCloud based one. 

I use it often to copy text on the phone then paste from my mac.

### Expected Behavior

Clicked on the password field should copy the value(it says value copied but does nothing)

### Steps to Reproduce

Click on a password entry
Click on the password field (it shows a pop up saying value copied) 

if you try to paste from other linked device will not have the value. 

### Debugging

- [ ] I did install the [TestFlight](https://testflight.apple.com/join/iuljLJ4u) version to check the log on the app's *Settings* page → *Log*.
- [ ] I did check for iOS logs named *Passwords* under *System Settings* → *Privacy & Security* → *Analytics & Improvements* → *Analytics Data*.
- [ ] I did check for Nextcloud logs on the admin's *Logging* page.

**Comment by johannes-schliephake** [comment]
Good point, thanks for all the details. I didn't want this to be enabled by default though, so I added a new settings toggle for Universal Clipboard. A TestFlight build should be available in the next hours (Build 40).
