### ISSUE TITLE
[Question] Should autofill also save password?

### ISSUE THREAD

**Issue by MarcusE1W** [johannes-schliephake/nextcloud-passwords-ios#29]
Hi.

Great app. Thanks for the effort.

From other passwd apps I noted that they pick up and save passwords they don’t know or that change during the autofill process.

is this a function that would be possible for this app as well, or should it already work ?

**Comment by johannes-schliephake** [comment]
Thanks for your positive feedback!

Unfortunately, this is mainly a limition of iOS. The only entry point I can take with this app is the button which appears above the keyboard when a login form is detected. iOS won't show a button to generate credentials during sign up.

However, I could optimize the user experience a little bit, i.e. by prepopulating the URL field of a new password entry if the user still opens the password provider via the keyboard. I'll look into it!

**Comment by destogl** [comment]
Hi @johannes-schliephake ,

Would it be possible to generate a new password on-the-fly. This means when password field is detected you open app and instead of choosing the existing password there is an option to generate a new one.

Thank for creating the app!

**Comment by johannes-schliephake** [comment]
Sounds really good, @destogl! I will definitely add something like this.
