### ISSUE TITLE
SSO & SAML-Authtication not working

### ISSUE THREAD

**Issue by Nomisimo** [johannes-schliephake/nextcloud-passwords-ios#291]
### iOS App Version

2.7.2

### iOS Version

16.6

### Device Model

iPhone 12 mini

### Nextcloud Server Version

28.06

### Server App Version

2024.5.20

### Peculiarities of Your Setup

I use the Nextcloud App `SSO & SAML-Authetification (v6.1.3)` together with Azure Ad for the LogIn flow. 

### Observed Behavior

During the login process in the iOS app, I am not redirected to Azure Ad for the login. Instead, I end up at the standard Nextlcoud login. However, this is only accessible in the instance under `/login?direct=1` and is otherwise deactivated 

### Expected Behavior

I should be automatically redirected to Azure Ad or Microsoft Login when I log in. 

### Debugging

- [x] I did install the [TestFlight](https://testflight.apple.com/join/iuljLJ4u) version to check the log on the app's *Settings* page → *Log*.
- [ ] I did check for iOS logs named *Passwords* under *System Settings* → *Privacy & Security* → *Analytics & Improvements* → *Analytics Data*.
- [ ] I did check for Nextcloud logs on the admin's *Logging* page.

**Comment by johannes-schliephake** [comment]
Thanks for reporting. Would it be possible for you to give me your server address for debugging? You can send me an Email at mail@cdslash.de if you want to.

**Comment by Nomisimo** [comment]
I sent you an e-mail.

**Comment by johannes-schliephake** [comment]
Solved via Email.
