### ISSUE TITLE
Passwords from other User

### ISSUE THREAD

**Issue by joleaf** [johannes-schliephake/nextcloud-passwords-ios#3]
Hi, thank you for your app (again :))

There is an issue when I login into another account.

Expected: The passwords from the new user are loaded.

Actual: The passwords from the previous user are visible. (The second one has e2e enabled)

Maybe flush the cache when the user logs out.

**Comment by johannes-schliephake** [comment]
Thanks for noticing and reporting this behavior!

Interestingly, this wasn't an issue with the local cache but rather a problem with the session. Even though this app uses stateless authentication, Nextcloud returns a valid session and continues to use it for all subsequent requests. I didn't think I'd have to clear a session when using stateless auth. Will probably take some time until I have fully grasped Nextcloud's API!

**Comment by johannes-schliephake** [comment]
Fixed with 5f723d2.

**Comment by huddx01** [comment]
> Hi, thank you for your app (again :))
> 
> There is an issue when I login into another account.
> 
> Expected: The passwords from the new user are loaded.
> 
> Actual: The passwords from the previous user are visible. (The second one has e2e enabled)
> 
> Maybe flush the cache when the user logs out.

@johannes-schliephake Really cool app, i was long waiting for

Have the same issue as @joleaf  

Additional hint: When I swipe to close/kill the app completly in iOS, then reopen, the correct passwords from the account are shown.
