### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by Visit-Digital** [johannes-schliephake/nextcloud-passwords-ios#31]
Hi! 
I setup the password app and an error occured. Please advise, thanks
![IMG_6555C50804E4-1](https://user-images.githubusercontent.com/79515925/108838062-6f40d080-75d3-11eb-8619-c91d9f077a14.jpeg)
![IMG_D392A9C2D80C-1](https://user-images.githubusercontent.com/79515925/108838075-723bc100-75d3-11eb-93f9-983ac46555e5.jpeg)

**Comment by johannes-schliephake** [comment]
Do you have end-to-end / client-side encryption enabled?

**Comment by Visit-Digital** [comment]
Hello, 

I have this
https://e.pcloud.link/publink/show?code=XZTBPkZyYnEceQ8iTYRiSnvR6jTsm5J5657

A master password is setup as well

Thanks for your help

Benoit

**Comment by johannes-schliephake** [comment]
Client-side encryption / a master password is currently not supported. #2 describes the same problem. Support for this feature is planned for the near future!

However, I will use this issue as an opportunity to maybe add a more detailed error message when the app can't connect due to client-side encryption being enabled.

**Comment by Visit-Digital** [comment]
Ok thanks! How do I disable the master password/E2E encryption I cannot figure it out

Thanks for support

**Comment by nefh** [comment]
If I am not mistaken, you can not. I had to "delete everything" in settings and set passwords from beginning. Of course by importing them.

**Comment by Visit-Digital** [comment]
Ok thanks, it all worked out!

**Comment by mohamnag** [comment]
For some (including me) disabling the end to end encryption is not an option, so I hope you will prioritize this feature high.
Thanks for all the effort

**Comment by johannes-schliephake** [comment]
Took the shortcut and E2E is now done, see #2.
