### ISSUE TITLE
Move the password box

### ISSUE THREAD

**Issue by OxideWaveLength** [johannes-schliephake/nextcloud-passwords-ios#40]
Imo the password box inside of the Edit view should be moved underneath the username box. Or maybe the first panel and the last one should be switched (I might be able to send a concept photo in a while)

**Comment by OxideWaveLength** [comment]
I was thinking of this as the first option:
![image](https://user-images.githubusercontent.com/60556091/110021132-a8dbaf00-7d2a-11eb-83e6-8c5a0f3b7c82.png)

(Also, maybe the password should be hidden in edit mode too, and shown just when tapped on, like in the View page).

The other option would be to just merge the two panels together and put the password bit right underneath the "Username" box

**Comment by OxideWaveLength** [comment]
Maybe this could also be an option. The settings page is a little empty...

**Comment by johannes-schliephake** [comment]
While this would work, I don't see the point from a usability perspective.

The password section is at the top of this view to be consistent with the password detail page, where it is also located at the top. If we change the position of the password section in either view we would have to do the same for the other view.

I think the layout of the password detail page is much more important as it is used a lot more. Therefore the order should be determined by the detail page where it makes the most sense to show the password at the top.

Nonetheless, I agree that the password should be hidden by default when editing.

**Comment by OxideWaveLength** [comment]
> The password section is at the top of this view to be consistent with the password detail page

Maybe it should be moved inside of the detail page as well, then. Having the username on top would be more intuitive, simply because that's how logins work, you don't really input your password first, do you.

 I have also gone through the App Store (and even G. Play Store) and I have yet to find one application in which the password field comes first, therefore the change would also make the switch from another password manager easier and would lead to a more consistent and intuitive experience.

> I think the layout of the password detail page is much more important as it is used a lot more.

Since this might boil down to preferences I think that this could easily become a setting.

**Comment by johannes-schliephake** [comment]
Alright, fair enough. Consistency with other password managers is also important.

However, I don't like the idea of just swapping the sections (notes aren't more important than the password). But just combining everything into one chunk would make it really disorganised.

New idea: What do you think of the following order?

Section "Service":
- Name
- URL

Section "Account":
- Username
- Password
- Show/hide password
- password generator (only when editing)

Section "Notes":
- Notes

This way username and password are shown together and the order is mostly by relevance.

**Comment by johannes-schliephake** [comment]
Although I closed this issue I'm of course still open to any ideas/improvements. In my opinion the new layout really makes sense and is thought through. I hope you like it! :)
