### ISSUE TITLE
Refreshing even when errors occour

### ISSUE THREAD

**Issue by OxideWaveLength** [johannes-schliephake/nextcloud-passwords-ios#42]
The refreshing functionality (scrolling down from the top) doesn't work when there is an error (as can be seen from [this video](https://youtu.be/ah-79PBXf_4). I'm not sure whether that's a big or is wanted, but I think that it should be added

**Comment by johannes-schliephake** [comment]
You're right, pull-to-refresh is currently not implemented (not even in the error view).

I will add this in the near future.

**Comment by OxideWaveLength** [comment]
I might be able to create a PR in the next days
