### ISSUE TITLE
Can‘t Login with End-to-End encryption enabled

### ISSUE THREAD

**Issue by zenzbert** [johannes-schliephake/nextcloud-passwords-ios#60]
Hi,

First of all thanks a lot for the app!!!
In passwords on Nextcloud one can enable End-to-End encryption. When I’m doing this, I can’t use any iOS App. Am I doing something wrong or is there a way to solve this.

I‘m using NC 20.0.4 and iOS App 1.2.1
To reconstruct just enable end to end encryption. But be careful, I think the only way back is to wipe all passwords data.

**Comment by zenzbert** [comment]
SORRY, just saw the closed Post. It should be working, thats great. Any Idea how i can find out, what i am missing?

**Comment by johannes-schliephake** [comment]
While I recently implemented E2E support, it is not yet published on the App Store. I'm still testing all changes and working on a few additional features. I hope to release the update next week or so.

**Comment by zenzbert** [comment]
awesome! Thanks a lot!
