### ISSUE TITLE
An error occurred...

### ISSUE THREAD

**Issue by skinrevolutionhk** [johannes-schliephake/nextcloud-passwords-ios#65]
**Version:** 20.0.5.2

**Build:** Ubuntu 20.04 LXD/LXC Ubuntu:20.04 Nextcloud Nginx, LXD/LXC Ubuntu:20.04 Nginx Reverse Proxy

S3 Primary Storage integrated.

Error | passman.   /appinfo/app.php is not loaded when \OCP\AppFramework\Bootstrap\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.

On the app side getting 'An error occured...' without further information.

Please help! Thanks :)

**Comment by johannes-schliephake** [comment]
The server error message indicates that you are using Passman, which isn't compatible with this app. If you are however using the Passwords Nextcloud app, the error is probably because you have CSE enabled. The upcoming update supports CSE.

**Comment by skinrevolutionhk** [comment]
Thank you so much! Did not know there are more password apps available! :_) 
Works Great
