### ISSUE TITLE
No keyboard visible, when try to enter unsaved E2E Password from Safari

### ISSUE THREAD

**Issue by huddx01** [johannes-schliephake/nextcloud-passwords-ios#72]
Hi Johannes,

thanks for the E2E Upgrade!

If i try to select my account data on a Page from the Safari on iPhone (current iOS), the nc-pw-app is correctly launched.
But i have the keyboard is not visible to be able to enter my E2E Password... 

Any Ideas?

**Comment by huddx01** [comment]
sorry... I have to tap into the box then the keyboard shows up

**Comment by huddx01** [comment]
Sorry... here is the screenshot about what i mean... in the red box - the keyboard should appear...

![e2e_without_saved_pw_from_safari](https://user-images.githubusercontent.com/25111146/121790149-b8e21500-cbdc-11eb-8ebb-ef8162635988.jpg)

**Comment by johannes-schliephake** [comment]
I've looked into this issue some time ago and unfortunately this is a bug in SwiftUI which I have no control over. iOS 15 will bring support for controlling keyboard and text field focus, but on iOS 14 we are out of luck. For now, the only fix is to close and reopen the provider once.
