### ISSUE TITLE
App not round on the App Store

### ISSUE THREAD

**Issue by azefgh456** [johannes-schliephake/nextcloud-passwords-ios#73]
Hello, I am on the French app store and the app cannot be found, whether on iPad or iPhone. When I try to airdrop the app to someone, the app store opens and the message that the app is not available in your region appears. However, I installed it barely 1 month ago.

**Comment by johannes-schliephake** [comment]
Hey, unfortunately I had to pull the app from the French App Store for the release of v2.0. This is the update which contains custom cryptography libraries for E2E encryption. The french authorities require every advanced cryptographic software to be declared, which is quite the process. I am currently dealing with the necessary paperwork, but am still struggling with a few sections. I hope to bring the app back soon to France!

**Comment by azefgh456** [comment]
Ok no problem, thanks for your work.

**Comment by maxime-killinger** [comment]
So do you have a TestFlight link for us to use the app ?

**Comment by johannes-schliephake** [comment]
It's not about how I distribute the app but the fact that I'm exporting cryptography to France. I'm sorry I can't make the app available to you right now, but it's super important to finish the paperwork first.

**Comment by azefgh456** [comment]
Any news for this issue? It's possible to skirt that with a TestFlight program?

**Comment by maxime-killinger** [comment]
> Any news for this issue? It's possible to skirt that with a TestFlight program?

Answer just here 

> It's not about how I distribute the app but the fact that I'm exporting cryptography to France. I'm sorry I can't make the app available to you right now, but it's super important to finish the paperwork first.

**Comment by jsalort** [comment]
@johannes-schliephake is there anyway we can help you with the paperwork (I'm french) ?

**Comment by johannes-schliephake** [comment]
Hey guys, sorry it took a while for an update.

It was important to me to finish anything iOS 15 related, which is now done with the upcoming v2.4. I am now putting my full attention towards this issue.

While I have already filled in the required papers, I'm stuck on a few problems. Mainly finding a way to distribute the app to the French authorities and understanding/preparing some additional documentation. @jsalort The last point is actually something where your help would be awesome! You can contact me via mail@cdslash.de so we can discuss the details.

**Comment by johannes-schliephake** [comment]
Good news! @jsalort and I prepared the necessary document and I just sent it to the French authorities. According to their website it will take about a month until they reply with further details.

**Comment by benoit-smith** [comment]
Great news indeed!
-------- Message d'origine --------De : Johannes Schliephake ***@***.***> Date : 24/11/2021  19:22  (GMT+01:00) À : johannes-schliephake/nextcloud-passwords-ios ***@***.***> Cc : Subscribed ***@***.***> Objet : Re: [johannes-schliephake/nextcloud-passwords-ios] App not round on the App Store (#73) 
Good news! @jsalort and I prepared the necessary document and I just sent it to the French authorities. According to their website it will take about a month until they reply with further details.

**Comment by Hacken-Dazs** [comment]
Not yet available on the app store in France ....

**Comment by eyona** [comment]
Hello,

Any idea when this app will be available on the french appstore ?

Regards

**Comment by johannes-schliephake** [comment]
I'm currently preparing additional documentation requested by the French government. I'm afraid I can't really give you an ETA.

**Comment by dacast** [comment]
Hi, I hope you can deliver documentaiton requested bu the French government. I really would like to use and spread your application with my family and friends. Good work !

Best,

**Comment by aldfeu** [comment]
BTW, maybe I can help you for the documentation for the french government. Please do not hesitate.

Regards

**Comment by johannes-schliephake** [comment]
Thanks for your support. Actually the documentation is completed and has been sent to to the French government in early January. Sadly I haven't heard back from them since, not even upon request.

Of course I will keep you all up to date and comment here and as soon as I get a response.

**Comment by mielune** [comment]
@johannes-schliephake Good luke for docs and French government.

**Comment by johannes-schliephake** [comment]
So I finally got a response from the French authorities yesterday ... stating that they are only now starting the actual review process. But at least the documentation seems to be complete.

**Comment by ascpial** [comment]
Let's hope it will be approved

**Comment by ogmkp** [comment]
I don't understand this nonsense, I'm sure that many crypto apps don't have to fill out documents with the French state, right ?

**Comment by johannes-schliephake** [comment]
@ogmkp What makes you think that?

Here are a few documents on the topic:
- Apple's documentation: https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations and https://help.apple.com/app-store-connect/#/devc3f64248f
- The French legal text: https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000646995/
- ANSSI's encryption control page: https://www.ssi.gouv.fr/en/regulation/cryptology/
- The initial document I had to send them: https://www.ssi.gouv.fr/uploads/2014/11/crypto_declaration-demande_autorisation_operations_annexe1_v2.pdf
- A blog post from Cryptomator giving an overview how their approval went: https://cryptomator.org/de/blog/2016/06/16/indepth-french-app-store/

**Comment by ogmkp** [comment]
@johannes-schliephake 

I know the process but I do not publish apps.
Is the same procedure for android or its just Apple who respect the law?

**Comment by johannes-schliephake** [comment]
@ogmkp I mean, it is the law in France. It is my responsibility to follow this law. Apple just has a very prominent process around export compliance, probably because they move around app related files from the USA to most other countries. To publish an Android app implementing non-exempt crypto via Google Play I definitely would have to go through the same approval process, it's just that Google won't explicitly ask me for those documents.

**Comment by johannes-schliephake** [comment]
I have good news for all of you! I finally did get full permission from the French government to export (i.e. publish) the app to France. I already uploaded the documents to the App Store, so now it's on Apple to review and approve the app for French users. I will post another update when the app is actually released. 

Funny side note: I actually received the permit from the French government as a physical letter. I kind of feel like framing this document.

**Comment by ogmkp** [comment]
Thank you for you effort !
Good news, I'm finally going to install it on my iOS after 4 months of waiting from my country !
Yes here in France, the administration is specialist in asking for papers by e-mail and answering us by physical mail.

**Comment by johannes-schliephake** [comment]
The app is now back in France's App Store! Now everyone finally has access to the iOS client. You can download/update the app here: [https://apps.apple.com/fr/app/id1546212226](https://apps.apple.com/fr/app/id1546212226). If you are updating, you can check the changelog from v2.0 to v2.6 to learn about all new features.

Thank you all for your patience and especially thank you @jsalort for helping me understand all those French words! Without you, this probably wouldn't have been possible.
