### ISSUE TITLE
Please App on ios no login 

### ISSUE THREAD

**Issue by JuanPerezPerez1** [johannes-schliephake/nextcloud-passwords-ios#84]
App in ios does not enter after putting the server. 
When you put the username and password it tells you to return to the page but does not enter the account, it returns to the page to put the server again

**Comment by johannes-schliephake** [comment]
Which iOS version do you run?

**Comment by JuanPerezPerez1** [comment]
I have nextcloud on my own server with syncloud yes

**Comment by johannes-schliephake** [comment]
Should be fixed now. The update might take a day or so until it's live on the App Store.

**Comment by JustinBack** [comment]
This behaviour is not limited to a subfolder though, I Installed Nextcloud on the root path without any subdomain and have the same issue. I am running on 2.1

**Comment by johannes-schliephake** [comment]
Interesting. Do you have "pretty URLs" (removes the index.php from URLs) set up on your instance? This is a case that I also missed in v2.1, but is fixed with v2.1.1 (on the App Store since a few hours ago).

**Comment by JustinBack** [comment]
Yep, url rewriting is enabled. I'll checkout the update in the mean time.

**Comment by JustinBack** [comment]
Can confirm it works with 2.1.1. Can be closed

**Comment by johannes-schliephake** [comment]
Awesome, that's great to hear. And thanks for testing!
