### ISSUE TITLE
use app password

### ISSUE THREAD

**Issue by Tealk** [johannes-schliephake/nextcloud-passwords-ios#94]
Hello,

I would like to log in to the app using an app password instead of creating a new one. Unfortunately the option is not selectable.

**Comment by johannes-schliephake** [comment]
This app currently uses Nextcloud's v2 login flow, which should work for every server setup. For now, I do not have plans to add other login options.

**Comment by Tealk** [comment]
then i don't understand why the option with the app password is not shown on the login page

I only noticed because I cleaned up all logins today and other apps have already shown this.

**Comment by johannes-schliephake** [comment]
For clarification: Do you mean the option for app passwords should show up when entering the server address or when the Nextcloud login is shown (the blue page)?

**Comment by Tealk** [comment]
> For clarification: Do you mean the option for app passwords should show up when entering the server address or when the Nextcloud login is shown (the blue page)?

The last one

**Comment by johannes-schliephake** [comment]
Ok, after taking a closer look at Nextcloud's login flow code, it seems that app passwords are only supported in Flow v1. For compatibility reasons Login Flow v2 is here to stay. It might be an option add app password support right into the app, but to be honest, this is not a highly requested feature.

Maybe it helps you to know that during the login process an app password is generated for you anyways. So this is only about reusing old app passwords, which isn't best practice in my opinion. So for a quick fix just delete your existing app password from Nextcloud's web settings and login in with this app.

**Comment by Tealk** [comment]
I use one app password for each device, so if I lose the device I only have to delete one app password.

**Comment by johannes-schliephake** [comment]
I just noticed that Nextcloud 24 added support for this. You can now log in using an app password during Flow v2. Here is the PR with some screenshots: nextcloud/server#29531
